name: Deploy Personal_Backend

on:
  release:
    types: [published]
  push:
    branches: [ "master" ]
      
jobs:
  deploy-docker-personal:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2

        - name: Docker meta
          id: meta
          uses: docker/metadata-action@v4
          with:
            images: ghcr.io/bernndd/web_engineering2
            flavor: latest=true
            tags: |
              type=ref,event=branch
              type=ref,event=pr
              type=semver,pattern={{version}}

        - name: Login to image repository
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build and push
          uses: docker/build-push-action@v3
          with:
            context: .
            file: ./src/Org.OpenAPITools/Dockerfile
            push: ${{ github.ref_type == 'tag' }}
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}

